"""
Agent 6: Report Agent

Phase 0 stub — passes state through unchanged and records that it ran.
"""

from __future__ import annotations

import logging
from src.orchestrator.state import AgentMLState

logger = logging.getLogger(__name__)

_PLACEHOLDER_REPORT = """
# AgentML Experiment Report (Phase 0 Placeholder)

This is a placeholder report generated by the stub pipeline.
Full content will be produced in Phase 6.

## Pipeline Status

All 7 agents executed successfully (as stubs).

## Next Steps

- Phase 1: Implement Dataset Profiling agent.
"""


def report_agent(state: AgentMLState) -> dict:
    """
    Report Agent stub.
    """
    logger.info("[report_agent] stub executed — writing placeholder report")
    return {
        "report_path": "outputs/reports/placeholder_report.md",
    }
